plugins {
    id 'fabric-loom' version '1.13-SNAPSHOT'
    id 'java'
}

group = 'com.rabimi'
version = '1.6.1'

repositories {
    maven {
        name = "Fabric"
        url = "https://maven.fabricmc.net/"
    }
    maven {
        name = "SonatypeSnapshots"
        url = "https://oss.sonatype.org/content/repositories/snapshots/"
    }
    maven { url = "https://keksuccino.github.io/maven/" }
    mavenCentral()
}

dependencies {
    minecraft "com.mojang:minecraft:1.21.11"
    mappings "net.fabricmc:yarn:1.21.11+build.4:v1"
    modImplementation "net.fabricmc:fabric-loader:0.18.4"
    modImplementation "net.fabricmc.fabric-api:fabric-api:0.141.3+1.21.11"
    modImplementation "de.keksuccino:mcef-fabric:2.2.0-1.21.11"
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

loom {
    mods{
        javaskinchanger{
            sourceSet sourceSets.main
        }
    }
    runs {
        client {
            ideConfigGenerated = true
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
    it.options.release = 21
}
