pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = "https://maven.terraformersmc.com/" }
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        gradlePluginPortal()
        maven { url = "https://keksuccino.github.io/maven/" }
        mavenCentral()
    }
}

rootProject.name = "JapanChat"